FROM registry.fedoraproject.org/fedora-toolbox:39

USER root

ARG NAME=vue_environment
LABEL name="$NAME" \
    summary="PHP 7.4 environment" \
    maintainer="Kingoftime"
ENV EDITOR=nano

RUN dnf -y upgrade \
    && dnf -y install https://rpms.remirepo.net/fedora/remi-release-39.rpm \
    && dnf -y install zsh \
    && dnf config-manager --set-enabled remi \
    && dnf module reset php -y \
    && dnf module install php:remi-7.4 -y

RUN php -r "copy('https://getcomposer.org/installer', 'composer-setup.php');" \
    && php -r "if (hash_file('sha384', 'composer-setup.php') === 'dac665fdc30fdd8ec78b38b9800061b4150413ff2e3b6f88543c636f7cd84f6db9189d43a81e5503cda447da73c7e5b6') { echo 'Installer verified'; } else { echo 'Installer corrupt'; unlink('composer-setup.php'); } echo PHP_EOL;" \
    && php composer-setup.php \
    && php -r "unlink('composer-setup.php');" \
    && sudo mv composer.phar /usr/local/bin/composer

