FROM registry.fedoraproject.org/fedora-toolbox:39

USER root

ARG NAME=flutter_environment
LABEL name="$NAME" \
    summary="Flutter environment" \
    maintainer="Kingoftime"

ENV EDITOR=nano


RUN dnf -y upgrade \
    && dnf -y install zsh

RUN git clone https://github.com/flutter/flutter.git /etc/flutter -b stable \
    && git config --global --add safe.directory /etc/flutter

ENV PATH="/etc/flutter/bin:/etc/flutter/bin/cache/dart-sdk/bin:${PATH}"
ENV TAR_OPTIONS="--no-same-owner"

RUN flutter doctor